### PR TITLE
closes #8 . Fixed the mass assignment in the profiles, events, and po…

### LINKED ISSUE #8: [Profile Controller] stop mass assigning
Ran a code climate, this was the biggest problem through out our controllers.

screen shot 2016-03-09 at 10 33 42 am

### PR DESCRIPTION
**Pull request by levans248**
…sts controllers by adding strong parameters.

### CODE REVIEW

**Comment by levans248** [comment]
Once this branch is reviewed and merged, I will fix issues 9-14

File: app/controllers/api/v1/posts_controller.rb [hunk 1]
```diff
@@ -25,4 +25,11 @@ def destroy
     Post.find(params[:id]).destroy
     format.json {render json: "Post Deleted"}
   end
+
+  private
+
+  def post_params
+    params.permit(:awesome_count, :description, :event_id, :feature_id, :photo, :user_id, :createdAt, :updatedAt)
```
Comment (zassmin) [inline app/controllers/api/v1/posts_controller.rb]: How come `createdAt` and `updatedAt` aren't underscores?

File: app/controllers/api/v1/profiles_controller.rb [hunk 2]
```diff
@@ -10,19 +10,16 @@ def show
   end
 
   def create
-    coordinates = Geocoder.coordinates(params[:location])
-    latitude = coordinates[0]
-    longitude = coordinates [1]
-    @profile = Profile.create(full_name: params[:full_name],image_url: params[:image_url], job_title: params[:job_title], latitude: params[:latitude], longitude: params[:longitude], network_id: params[:network_id], photo: params[:photo], theme_type: params[:theme_type], user_id: current_user.id, createdAt: params[:createdAt], updatedAt: params[:updatedAt])
+    coordinates = get_coordinates(params[:location])
```
Comment (zassmin) [inline app/controllers/api/v1/profiles_controller.rb]: it also makes sense to use strong params for `params[:location]`

File: app/controllers/api/v1/profiles_controller.rb [hunk 3]
```diff
@@ -10,19 +10,16 @@ def show
...
+    @profile = Profile.create(profile_params)
+    @profile.update_attributes(latitude: coordinates[0], longitude: coordinates[1])
```
Comment (zassmin) [inline app/controllers/api/v1/profiles_controller.rb]: also, when accessing the first or last element from an array, prefer `first` or `last` over `[0] or `[1]`. I'm assuming `[1]` is being referred to as the last element in this case?

**Comment by zassmin** [comment]
@levans248 thanks for submitting made a few comments. 

Again, 

the best way to reference the issue in a PR is like so...

closes #9 
closes #10 

...this way github can auto close the issue. I think it only works when it's in the first comment

https://github.com/blog/1506-closing-issues-via-pull-requests

The issue you referenced in the commit message 'should' auto close per https://help.github.com/articles/closing-issues-via-commit-messages/

File: app/controllers/api/v1/posts_controller.rb (hunk 1 above)
Comment (levans248) [inline app/controllers/api/v1/posts_controller.rb]: That is how the API team set it up originally.  I am not entirely sure why it is necessary to even include a createdAt and updatedAt since the database usually tracks this automatically.

File: app/controllers/api/v1/profiles_controller.rb (hunk 3 above)
Comment (levans248) [inline app/controllers/api/v1/profiles_controller.rb]: Okay thanks. I will change.

File: app/controllers/api/v1/profiles_controller.rb (hunk 2 above)
Comment (levans248) [inline app/controllers/api/v1/profiles_controller.rb]: Okay, I will add it.

File: app/controllers/api/v1/posts_controller.rb (hunk 1 above)
Comment (zassmin) [inline app/controllers/api/v1/posts_controller.rb]: ya, I was thinking they put in there as a way for the client to pass in the timestamp, incase there are any delays. It looks like there are both timestamps and createdAt columns in the schema, 
https://github.com/WomenWhoCode/wwcode_api/blob/master/db/schema.rb#L28
https://github.com/WomenWhoCode/wwcode_api/blob/master/db/schema.rb#L33
I'll open up an issue asking that question.

File: app/controllers/api/v1/profiles_controller.rb [hunk 4]
```diff
@@ -10,19 +10,16 @@ def show
...
   end
 
   def update
     @profile = Profile.find(params[:id])
-    coordinates = Geocoder.coordinates(params[:location])
-    latitude = coordinates[0]
-    longitude = coordinates [1]
-    @profile.update(full_name: params[:full_name],image_url: params[:image_url], job_title: params[:job_title], latitude: params[:latitude], longitude: params[:longitude], network_id: params[:network_id], photo: params[:photo], theme_type: params[:theme_type], user_id: current_user.id, createdAt: params[:createdAt], updatedAt: params[:updatedAt])
+    coordinates = get_coordinates(location_param)
+    @profile.update_attributes(profile_params, latitude: coordinates[first], longitude: coordinates[last])
```
Comment (zassmin) [inline app/controllers/api/v1/profiles_controller.rb]: Since `#get_coordinates` returns an array, to access the array elements using `first` and `last` we'd do `coordinates.first` and `coordinates.last`

**Comment by zassmin** [comment]
@levans248 :+1: I made one more comment, otherwise it's good to go.

**Comment by zassmin** [comment]
:+1: :100:
